module.exports = {
    name: "Logging of the TAS and the SUT",
    keyPoints: [
        {
            name:"TAS logging should include the following",
            pointSummary: [
                `Which test case is currently under execution, including start and end time.`,
                `The status of the test case execution`,
                `Details of the test log at a high level including timing information`,
                `Dynamic information about the SUT 
                    with the test case that revealed this info`,
                `A counter for repeated tests`,
                `Random data, generated by the test`,
                `Test case actions`,
                `Screenshots and other visual data`,
                `Details on failure`,
                `Storing logs persistently`,
                `Colors to distinguish different types of information`
            ]
        },
        {
            name:"SUT logging:",
            pointSummary: [
                `In case of a failure SUT should log 
                    date and time stamps, 
                    source location of issue, error messages`,
                `SUT can log all user interaction`,
                `At startup of the system, configuration information should be logged to a file`,
            ]
        }
    ]
}